### ISSUE TITLE
Bad text adjustment on one subpage when Polish lang is chosen

### ISSUE THREAD

**Issue by atlochowski** [Kormil/harbour-powietrze#11]
On Jolla 1

![Zrzut_ekranu_20200330_001](https://user-images.githubusercontent.com/5940803/77949248-ea680c80-72c6-11ea-8a8b-0f8d9a32e353.png)

**Comment by Kormil** [comment]
Hi, fix will be release with next version. I just add word wrap to these labels. If you don't want to wait, you can change „Nazwy zanieczyszczeń/Pollution names" in settings and set it on „Short/Skrócone”

**Comment by Kormil** [comment]
Released in 1.4.2
