### ISSUE TITLE
"Air quality index" setting is not saved for Airly

### ISSUE THREAD

**Issue by Olf0** [Kormil/harbour-powietrze#4]
If *Settings ->* ***>*** *-> Airly -> Air quality index* is set to "European air quality index" it is always reset to its default "The Common Air Quality Index" when restarting Powietrze.
The corresponding setting for the Powietrze data provider is working fine (including "long" / "short").

Tested with Powietrze 1.2.2

**Comment by Kormil** [comment]
Fixed in 1.3.0

**Comment by Olf0** [comment]
Thank you for commit https://github.com/Kormil/harbour-powietrze/commit/c0d4494358cba223c44bfae7ff9fc47b0e251c43

**Comment by Olf0** [comment]
Working fine on a Jolla1@SFOS2.2.1
