### ISSUE TITLE
Source footer overlaps with page content

### ISSUE THREAD

**Issue by Olf0** [Kormil/harbour-powietrze#5]
Thanks for the visual enhancements in v1.3.0!

I didn't consider this worth to file an issue, but as your are paying attention to nice, little details as the gradient "underlay" for the values:
The data source footer on a results page always overlays the data values, if the value list is long enough to reach it (which always is the case for landscape orientation in a Jolla 1).

BTW, this occurs with all (three) data providers.

Suggestions:
* (Easiest) Eliminate the footer, as the data source is also displayed in the column right to the smiley since v1.3.0
* (Second easiest) Convert the footer to a fixed element at the bottom of a results page (i.e., not overlayed anymore).
* (Supposedly hardest) Let the footer occupy a fixed space at the bottom of the screen, so it is always visible, and shrink the height of a results page by the footer height.

Example:
![Screenshot_20191129_001](https://user-images.githubusercontent.com/16547876/69834593-9aefd200-123b-11ea-9d7b-04688a519a58.png)

**Comment by Kormil** [comment]
Hi, i had flu for a few days so i almost die :P. Now i come back, fix bugs and release new version. I think my idea will work: bb35519

**Comment by Olf0** [comment]
Thanks, Powietrze 3.1.3 is looking really great, its footer implementation is cool!

Minor suggestions:
- Make all (currently three different) footers one-liners, by converting the footer for Airly from
`Data by airapi.airly.eu`
`    map.airly.eu    `
to
`Data by airapi.airly.eu & map.airly.eu`
- Reserve a little space above the footer (which "belongs" to the footer, i.e. is part of it), as it is already the case below the footer (approximately 1/4 to 1/3 of the line height), so it looks more like this (the space above the footer is a little bit too large in this constructed example) ![Screenshot_20191208_002](https://user-images.githubusercontent.com/16547876/70396704-a2696500-1a0b-11ea-8ce0-822232038f5c.png) than this ![Screenshot_20191208_001](https://user-images.githubusercontent.com/16547876/70396712-ba40e900-1a0b-11ea-80dc-76e0457bfdcf.png)

**Comment by Olf0** [comment]
... and good to know that you are well again.  😄
