### ISSUE TITLE
Distance to station is not shown for OpenAQ

### ISSUE THREAD

**Issue by Olf0** [Kormil/harbour-powietrze#6]
The distance to the selected station is not shown on result pages for OpenAQ in v1.3.0.  In contrast to that the distance is nicely displayed at result pages from Powietrze and Airly.
Displayed the distance to station is a nice enhancement in v1.3.0, thanks.

Examples:
* Missing distance for stations from OpenAQ: ![Screenshot_20191129_002](https://user-images.githubusercontent.com/16547876/69834771-ddfe7500-123c-11ea-9fd2-818b4f31a186.png)
* Distance is nicely displayed for stations from Powietrze (and Airly): ![Screenshot_20191129_001](https://user-images.githubusercontent.com/16547876/69834593-9aefd200-123b-11ea-9d7b-04688a519a58.png)

**Comment by Kormil** [comment]
Airly stations had this issue too. Only stations which was not far more than 8km during gps locating and ones from Powietrze had valid distance. Should be fixed in 1.3.1.

**Comment by Olf0** [comment]
It is.
Thank you!
